name: Github Actions Demo
on: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup java environment
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 11
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: mvn clean install -DskipTests
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup java environment
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 11
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: mvn test