name: Github Actions Demo
on: 
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup java environment
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 11
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: mvn clean install -DskipTests
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup java environment
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 11
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: mvn test
  release_snapshot:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo ${{ secrets.JFROG_USERNAME }}
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 11
          server-id: "snapshots"
          server-username: ${{ secrets.JFROG_USERNAME }}
          server-password: ${{ secrets.JFROG_PASSWORD }}
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: mvn deploy